# Generated by Django 5.2.12 on 2026-04-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_variation_category_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
