# Generated by Django 5.2.12 on 2026-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
