# Generated by Django 5.2.12 on 2026-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
